### ISSUE TITLE
"ext" property

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-svg#1]
is it necessary to put 
```
"ext": {
      "svg": "steal-svg"
    }
```

to the apps package.json?  

i think the `ext` property should be on this repo package.json, like the steal-css does
https://github.com/stealjs/steal-css/blob/master/package.json#L35-L38

**Comment by marshallswain** [comment]
Oh, hey.  I'm going to try that.

**Comment by marshallswain** [comment]
Published as `steal-svg@0.0.5`.   Thanks!
